### ISSUE TITLE
localization 

### ISSUE THREAD

**Issue by GoogleBeEvil** [xn-twist/XNfire#1]
var msg = `Warning: the actual domain you visited is "${hostname}". This is an internationalized domain name (IDN).
If the address bar appears to show a site you were intending to visit, you should not enter any information here, leave the page and type the site manually.`

Better show diffrent LANG by firefox default LANG,for Chinese，it is

var msg = `警告: 您当前所访问的网站真实域名为 "${hostname}". 这是一个国际化域名 (IDN技术).如果地址栏显示一个与真实域名不一致的地址栏(通常是伪造个高仿地址)，不要在此网站输入任何信息密码等，关闭此页面手动输入你需要访问的页面`

And, I think it's better to show what IDN is to normal user (add redirect link to wiki https://en.wikipedia.org/wiki/IDN_homograph_attack)

**Comment by fhightower** [comment]
Thanks for raising this issue! If you'd like to contribute, we'd be happy to consider a PR.
